namespace Super_Auto_Mobs
{
    public enum CharacterEnum
    {
        CaptainEugene,
        Palesos,
        Zak,
        Bav,
        Notch,
        Moddychat,
        SirPiligrim,
        ModdychatDeath,
        Nerkin,
        Alfedov,
        Diamkey,
        Alcest,
        Venazar,
        Heo,
        Dushenka,
        KrolikMun,
        Just,
        ObsidianTime,
        PWGood,
        Zakviel,
        MoDDyChat,
        SnrGiraffe,
        Wyvernna,
        NeadApTar
    }
}