namespace Super_Auto_Mobs
{
    public enum MobEnum
    {
        Cat,
        Dog,
        Villager,
        Zombie,
        SnowGollum,
        Skeleton,
        Duck,
        Chocobo,
        Enderman,
        MushroomCow,
        MilkaCow,
        Creeper,
        Bee,
        Squid,
        Witch,
        VillagerBig,
        Test,
        Chicken,
        Palesos,
        Notch,
        ModdychatDeath,
        Moddychat,
        Zak,
        SirPiligrim,
        Bav
    }
}